name: Branch Name Check

on:
  pull_request:
    branches:
      - dev
      - main

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        run: |
          echo "PR branch: $GITHUB_HEAD_REF"
          if [[ ! "$GITHUB_HEAD_REF" =~ ^(feature|fix|dependabot)/[a-z0-9._-]+$ ]]; then
            echo "❌ Invalid branch name. Use 'feature/*' or 'fix/*'."
            exit 1
          fi
          echo "✅ Branch name is valid"
