name: Angular Build and Deploy

on:
  push:
    branches:
      - dev
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
  
      - name: Install dependencies
        run: npm install
  
      - name: Verify Node and NPM versions
        run: |
          node -v
          npm -v
      - name: Verify Angular CLI Version
        run: ./node_modules/.bin/ng --version
      - name: Debug node_modules/.bin
        run: ls -al ./node_modules/.bin
  
      - name: Build Angular app (Development)
        if: github.ref != 'refs/heads/main'
        run: ./node_modules/.bin/ng build --configuration=development

      - name: Set deploy dir
        run: |
          echo "DEPLOY_DIR=${{ github.ref == 'refs/heads/main' && './www' || './develop/www' }}" >> $GITHUB_ENV

      - name: Deploy via FTP
        uses: airvzxf/ftp-deployment-action@latest
        with:
          server: ${{ secrets.CD_FTP_SERVER }}
          user: ${{ secrets.CD_FTP_USERNAME }}
          password: ${{ secrets.CD_FTP_PASSWORD }}
          local_dir: "./dist/webovky"
          remote_dir: ${{ env.DEPLOY_DIR }}
          delete: "true"

      - name: Clean up
        run: rm -rf ./dist